### ISSUE TITLE
Online images not scaling well 

### ISSUE THREAD

**Issue by mkevin1993** [virtualvivek/BlurShadowImageView#3]
Online images loaded buy Picasso/Glide rendered incorrectly.

API LEVEL 30
**REPRODUCTION.**

Using the demo app i resized the ImageView to fill the width and have height same as width. After clicking "Load Online Image" button, the image is not scaling to fit the new width and height.

**Screenshot shows local image scaling well:**

![Screenshot_Before](https://user-images.githubusercontent.com/33483297/128224256-3a90b822-0057-446e-b437-1057359ea2e7.jpg)

----------------------------------------------------------------------------

**Screenshot when loading online image:**

----------------------------------------------------------------------

![Screenshot_after](https://user-images.githubusercontent.com/33483297/128224461-9e9c5763-23dc-4662-b1be-946d11c56d95.jpg)

**Comment by virtualvivek** [comment]
Hi @mkevin1993 ,

Greetings for the day, 
As from the above screenshots we are able to see something has a bug but its not clear what was happening under the hood,

Can you please share some code stuff including the .XML file and .JAVA/.Kotlin File that is encountering the issue.

**Comment by mkevin1993** [comment]
here is xml code. It's from the example in the code. The first ImageView's width and height are 400dp each. After the app opening, the local image scales well. After clicking the "Load Online Image" button, the resulting image is not scaled to fit the view no matter what scale type is used. The activity code is the same as in the app example. Thanks

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="me.virtualiz.blurshadowimageviewEx.MainActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:orientation="horizontal"
        android:translationZ="2dp"
        android:background="#FAFAFA"
        android:elevation="2dp">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:text="@string/app_name"
            android:textSize="19sp"
            android:layout_gravity="center"
            android:gravity="center"
            android:textColor="#444"/>
    </LinearLayout>

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:layout_marginBottom="5dp"
                android:layout_marginTop="20dp"
                android:gravity="center"
                android:text="Library provides iOS style backdrop shadows to Imageview"
                android:textSize="15sp" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:text="[     API 21+     ]"
                android:textColor="#16ab9c"
                android:textStyle="bold"
                android:textSize="12.4sp"
                android:layout_marginBottom="5dp"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:text="Find it on"
                android:textStyle="bold"
                android:layout_marginBottom="5dp"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/link_text"
                android:layout_gravity="center"
                android:layout_marginBottom="10dp"
                android:textColor="#16ab9c"
                android:textStyle="bold"
                android:text="github.com/virtualvivek/BlurShadowImageView"/>


            <Button
                style="@style/Base.Widget.AppCompat.Button.Borderless"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/buttonLink"
                android:text="Project on Github"
                android:background="@drawable/background_white_round_touchlistner_selector"
                android:layout_marginBottom="32dp"
                android:layout_marginTop="5dp"
                android:layout_marginRight="20dp"
                android:layout_marginLeft="20dp"
                android:textColor="#444"
                android:textAllCaps="false"
                android:textSize="16sp"
                android:drawableStart="@drawable/github"
                android:paddingLeft="25dp"
                android:paddingRight="25dp"/>

            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:layout_width="400dp"
                android:layout_height="400dp"
                android:layout_gravity="center"
                android:id="@+id/demo_img"
                android:scaleType="centerInside"
                app:v_imageSrc="@drawable/lambo"/>

            <Button
                style="@style/Base.Widget.AppCompat.Button.Borderless"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/buttonLoadImg"
                android:text="Load Online Image"
                android:background="@drawable/background_green_round_touchlistner_selector"
                android:layout_marginBottom="32dp"
                android:layout_marginTop="5dp"
                android:layout_marginRight="20dp"
                android:layout_marginLeft="20dp"
                android:textSize="16sp"
                android:textColor="@android:color/white"
                android:textAllCaps="false" />

            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:layout_width="200dp"
                android:layout_height="220dp"
                android:layout_gravity="center"
                android:layout_marginBottom="24dp"
                app:v_imageSrc="@drawable/ironman" />


            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:layout_width="255dp"
                android:layout_height="200dp"
                android:layout_gravity="center"
                android:layout_marginBottom="24dp"
                app:v_imageRound="0dp"
                app:v_imageSrc="@drawable/product_garments" />


            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:layout_width="200dp"
                android:layout_height="220dp"
                android:layout_gravity="center"
                android:layout_marginBottom="24dp"
                app:v_imageRound="20dp"
                app:v_imageSrc="@drawable/nature" />


            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:layout_width="280dp"
                android:layout_height="220dp"
                android:layout_gravity="center"
                android:layout_marginBottom="74dp"
                app:v_imageRound="15dp"
                app:v_imageSrc="@drawable/lambo" />


        </LinearLayout>

    </ScrollView>


</LinearLayout>
`

**Comment by polonez-byte-112** [comment]
Same error  

```
            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:id="@+id/playerSongImg"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:layout_marginTop="50dp"
                android:layout_marginBottom="50dp"
                android:scaleType="fitCenter"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />
```

**Comment by virtualvivek** [comment]
Hi @mkevin1993 , @polonez-byte-112 ,
I try to resolve this issue asap,
If you have any suggestions where it is giving us the issue you can also comment here,
When i get into any conclusion will notify you here.

**Comment by virtualvivek** [comment]
Hi Guys i have tested this in below API 30 and this bug is also there,
Just try to fix this and let notify you.

**Comment by virtualvivek** [comment]
Hi @mkevin1993 , @polonez-byte-112 ,

I have Fixed this issue can you please check this from your side and let me know
‣ now for **`BlurShadowImageView -v4.0`**
# 😊

**Comment by polonez-byte-112** [comment]
Thanks I will try 💯

**Comment by polonez-byte-112** [comment]
Work's amazing. Good work Bro 
Result : https://imgur.com/a/OhqqMJ4

**Comment by polonez-byte-112** [comment]
Thanks for helping this issue ❤️

**Comment by polonez-byte-112** [comment]
Got one issue still .Shadow is too big by default. I have picture make fill_parent and fitCenter .I will add code below

**Comment by polonez-byte-112** [comment]
Here's how Currently I am setting UI  . Preview: https://imgur.com/a/yvrZjpO

```
   <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/playerSmallBox"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_marginLeft="50dp"
            android:layout_marginRight="50dp"
            android:layout_weight="1"
            android:gravity="bottom"
            app:layout_constraintEnd_toStartOf="@+id/playerSongImg"
            app:layout_constraintStart_toStartOf="@+id/playerSongImg">


            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:id="@+id/playerSongImg"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:layout_marginTop="50dp"
                android:layout_marginBottom="50dp"
                android:scaleType="fitCenter"
                app:v_imageRound="20dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />


        </androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by polonez-byte-112** [comment]
Preview: https://imgur.com/a/OdbgTU6
Code: 
```
        <androidx.constraintlayout.widget.ConstraintLayout
            android:id="@+id/playerSmallBox"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_marginLeft="50dp"
            android:layout_marginRight="50dp"
            android:layout_weight="1"
            android:gravity="bottom"
            app:layout_constraintEnd_toStartOf="@+id/playerSongImg"
            app:layout_constraintStart_toStartOf="@+id/playerSongImg">


            <me.virtualiz.blurshadowimageview.BlurShadowImageView
                android:id="@+id/playerSongImg"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:layout_marginTop="50dp"
                android:layout_marginBottom="50dp"
                android:scaleType="fitCenter"
                app:v_imageRound="0dp"
                app:v_shadowOffset="0dp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintHorizontal_bias="0.5"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />


        </androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by polonez-byte-112** [comment]
Also after glide load , image round disapears. I guess that's why I have still shadow. But  I dont have function to manualy set it

**Comment by mkevin1993** [comment]
> Hi @mkevin1993 , @polonez-byte-112 ,
> 
> I have Fixed this issue can you please check this from your side and let me know
> ‣ now for **`BlurShadowImageView -v4.0`**
> 
> #

Its fixed. Thanks

**Comment by virtualvivek** [comment]
> Also after glide load , image round disapears. I guess that's why I have still shadow. But I dont have function to manualy set it

To use it with Glide you can use the callback method to set Image

```java
BlurShadowImageView your_blurshadowimageview = findViewById(R.id.your_blurSImageView);

Glide.with(this)
        .asBitmap()
        .load(imagePath)
        .into(new CustomTarget<Bitmap>() {
            @Override
            public void onResourceReady(@NonNull Bitmap resource, @Nullable Transition<? super Bitmap> transition) {
                your_blurshadowimageview.setImageBitmap(resource);
            }

            @Override
            public void onLoadCleared(@Nullable Drawable placeholder) {
            }
   });
```

If it resolves your issue let me know.

**Comment by virtualvivek** [comment]
> Preview: https://imgur.com/a/OdbgTU6
> Code:
> 
> ```
>         <androidx.constraintlayout.widget.ConstraintLayout
>             android:id="@+id/playerSmallBox"
>             android:layout_width="match_parent"
>             android:layout_height="0dp"
>             android:layout_marginLeft="50dp"
>             android:layout_marginRight="50dp"
>             android:layout_weight="1"
>             android:gravity="bottom"
>             app:layout_constraintEnd_toStartOf="@+id/playerSongImg"
>             app:layout_constraintStart_toStartOf="@+id/playerSongImg">
> 
> 
>             <me.virtualiz.blurshadowimageview.BlurShadowImageView
>                 android:id="@+id/playerSongImg"
>                 android:layout_width="fill_parent"
>                 android:layout_height="fill_parent"
>                 android:layout_marginTop="50dp"
>                 android:layout_marginBottom="50dp"
>                 android:scaleType="fitCenter"
>                 app:v_imageRound="0dp"
>                 app:v_shadowOffset="0dp"
>                 app:layout_constraintBottom_toBottomOf="parent"
>                 app:layout_constraintEnd_toEndOf="parent"
>                 app:layout_constraintHorizontal_bias="0.5"
>                 app:layout_constraintStart_toStartOf="parent"
>                 app:layout_constraintTop_toTopOf="parent" />
> 
> 
>         </androidx.constraintlayout.widget.ConstraintLayout>
> ```

That looks more clean and perfect!
Can the same results be get using less value on **app:v_shadowOffset="40dp"**

**Comment by polonez-byte-112** [comment]
Thanks Bro 😁. I got inspired by Spotify Check preview on my github profile. I also have gif's like Spotify do (Downloaded from their platform).

 About Shadow size I tried everything and I dont know if this fill parent (img) is, responsible for that. I think You can close Issue 😁.

**Comment by virtualvivek** [comment]
> > Hi @mkevin1993 , @polonez-byte-112 ,
> > I have Fixed this issue can you please check this from your side and let me know
> > ‣ now for **`BlurShadowImageView -v4.0`**
> 
> Its fixed. Thanks

Hi @mkevin1993 i was just waiting for your reply.
So the issue is fixed we can now close this opened issue.

**Comment by virtualvivek** [comment]
> Thanks Bro . I got inspired by Spotify Check preview on my github profile. I also have gif's like Spotify do (Downloaded from their platform).
> 
> About Shadow size I tried everything and I dont know if this fill parent (img) is, responsible for that. I think You can close Issue .

Ya I have checked your work that is amazing keep it up buddy!
